[package]
name = "web-audio-api"
version = "0.1.0"
authors = ["Otto <otto@ot-to.nl>"]
edition = "2018"
description = "A Rust implementation of the Web Audio API, for use in non-browser contexts"
readme = "README.md"
repository = "https://github.com/orottier/web-audio-api-rs"
keywords = ["web-audio-api", "audio", "sound"]
license = "MIT"
categories = ["multimedia::audio"]

[dependencies]
