// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.36.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'message_port.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Resampler>>
@sealed
class Resampler extends RustOpaque {
  Resampler.dcoDecode(List<dynamic> wire) : super.dcoDecode(wire, _kStaticData);

  Resampler.sseDecode(BigInt ptr, int externalSizeOnNative)
      : super.sseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_Resampler,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_Resampler,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_ResamplerPtr,
  );

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<Resampler> newInstance(
          {required double sampleRate,
          required BigInt sampleLen,
          required M input,
          dynamic hint}) =>
      RustLib.instance.api.crateApiResamplingResamplerNew(
          sampleRate: sampleRate,
          sampleLen: sampleLen,
          input: input,
          hint: hint);
}
