// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.36.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Stream<LogEntry> traceLogger({dynamic hint}) =>
    RustLib.instance.api.crateApiSimpleTraceLogger(hint: hint);

Future<bool> initTauCore({dynamic hint}) =>
    RustLib.instance.api.crateApiSimpleInitTauCore(hint: hint);

Future<void> rustSetLogLevel({required int level, dynamic hint}) =>
    RustLib.instance.api
        .crateApiSimpleRustSetLogLevel(level: level, hint: hint);

Future<String> greet({required String name, dynamic hint}) =>
    RustLib.instance.api.crateApiSimpleGreet(name: name, hint: hint);

enum Level {
  error,
  warn,
  info,
  debug,
  trace,
  ;
}

class LogEntry {
  final PlatformInt64 timeMillis;
  final String msg;
  final Level logLevel;
  final String lbl;

  const LogEntry({
    required this.timeMillis,
    required this.msg,
    required this.logLevel,
    required this.lbl,
  });

  @override
  int get hashCode =>
      timeMillis.hashCode ^ msg.hashCode ^ logLevel.hashCode ^ lbl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LogEntry &&
          runtimeType == other.runtimeType &&
          timeMillis == other.timeMillis &&
          msg == other.msg &&
          logLevel == other.logLevel &&
          lbl == other.lbl;
}
