// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.36.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'analyser.dart';
import 'audio_node.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// The type `ChannelMergerRenderer` is not used by any `pub` functions, thus it is ignored.

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ChannelMergerNode>>
@sealed
class ChannelMergerNode extends RustOpaque {
  ChannelMergerNode.dcoDecode(List<dynamic> wire)
      : super.dcoDecode(wire, _kStaticData);

  ChannelMergerNode.sseDecode(BigInt ptr, int externalSizeOnNative)
      : super.sseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_ChannelMergerNode,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_ChannelMergerNode,
    rustArcDecrementStrongCountPtr: RustLib
        .instance.api.rust_arc_decrement_strong_count_ChannelMergerNodePtr,
  );

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<ChannelMergerNode> newInstance(
          {required C context,
          required ChannelMergerOptions options,
          dynamic hint}) =>
      RustLib.instance.api.crateApiNodeChannelMergerChannelMergerNodeNew(
          context: context, options: options, hint: hint);
}

/// Options for constructing a [`ChannelMergerNode`]
class ChannelMergerOptions {
  final BigInt numberOfInputs;
  final AudioNodeOptions audioNodeOptions;

  const ChannelMergerOptions({
    required this.numberOfInputs,
    required this.audioNodeOptions,
  });

  @override
  int get hashCode => numberOfInputs.hashCode ^ audioNodeOptions.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChannelMergerOptions &&
          runtimeType == other.runtimeType &&
          numberOfInputs == other.numberOfInputs &&
          audioNodeOptions == other.audioNodeOptions;
}
