// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.36.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'analyser.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<MediaStreamTrackAudioSourceNode>>
@sealed
class MediaStreamTrackAudioSourceNode extends RustOpaque {
  MediaStreamTrackAudioSourceNode.dcoDecode(List<dynamic> wire)
      : super.dcoDecode(wire, _kStaticData);

  MediaStreamTrackAudioSourceNode.sseDecode(
      BigInt ptr, int externalSizeOnNative)
      : super.sseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount: RustLib.instance.api
        .rust_arc_increment_strong_count_MediaStreamTrackAudioSourceNode,
    rustArcDecrementStrongCount: RustLib.instance.api
        .rust_arc_decrement_strong_count_MediaStreamTrackAudioSourceNode,
    rustArcDecrementStrongCountPtr: RustLib.instance.api
        .rust_arc_decrement_strong_count_MediaStreamTrackAudioSourceNodePtr,
  );

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<MediaStreamTrackAudioSourceNode> newInstance(
          {required C context,
          required MediaStreamTrackAudioSourceOptions options,
          dynamic hint}) =>
      RustLib.instance.api
          .crateApiNodeMediaStreamTrackSourceMediaStreamTrackAudioSourceNodeNew(
              context: context, options: options, hint: hint);
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<& 'a MediaStreamTrack>>
@sealed
class AMediaStreamTrack extends RustOpaque {
  AMediaStreamTrack.dcoDecode(List<dynamic> wire)
      : super.dcoDecode(wire, _kStaticData);

  AMediaStreamTrack.sseDecode(BigInt ptr, int externalSizeOnNative)
      : super.sseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_AMediaStreamTrack,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_AMediaStreamTrack,
    rustArcDecrementStrongCountPtr: RustLib
        .instance.api.rust_arc_decrement_strong_count_AMediaStreamTrackPtr,
  );
}

/// Options for constructing a [`MediaStreamTrackAudioSourceNode`]
class MediaStreamTrackAudioSourceOptions {
  final AMediaStreamTrack mediaStreamTrack;

  const MediaStreamTrackAudioSourceOptions({
    required this.mediaStreamTrack,
  });

  @override
  int get hashCode => mediaStreamTrack.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MediaStreamTrackAudioSourceOptions &&
          runtimeType == other.runtimeType &&
          mediaStreamTrack == other.mediaStreamTrack;
}
